image:
  file: Dockerfile
tasks:
  - before:
      pg_start.sh
  - init:
      bundle install
  - command:
      RACK_ENV=gitpod bundle exec rake db:create &&
      RACK_ENV=gitpod bundle exec rake db:migrate
