image:
  file: Dockerfile
tasks:
  - before:
      pg_start.sh
  - init:
      bundle install &&
      yarn install
  - command:
      RAILS_ENV=gitpod bundle exec rake db:create &&
      RAILS_ENV=gitpod bundle exec rake db:migrate
